server:
  port: 8771

spring:
  application:
    name: staff
  datasource:
    username: root
    password: 129431075
    url: jdbc:mysql://127.0.0.1:3306/staff_management?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  transaction:
    rollback-on-commit-failure: true
    default-timeout: 5000

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.staff.entity


#指定注册中心地址
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/



